### ISSUE TITLE
Add ollama models fails

### ISSUE THREAD

**Issue by ziyic** [myshell-ai/AIlice#38]
Seems something wrong when I attempt adding ollama models

I got following info

```
We now start the vector database. Note that this may include downloading the model weights, so it may take some time.
Encountered an exception, AIlice is exiting: Failed to create llama_context
  File "/Users/ziyic/AIlice/ailice/AIliceWeb.py", line 225, in main
    mainLoop(**kwargs)
  File "/Users/ziyic/AIlice/ailice/AIliceWeb.py", line 60, in mainLoop
    msg = storage.Open("")
  File "/Users/ziyic/AIlice/ailice/common/lightRPC.py", line 106, in methodTemplate
    return self.RemoteCall(methodName,args,kwargs)
  File "/Users/ziyic/AIlice/ailice/common/lightRPC.py", line 129, in RemoteCall
    raise ret['exception']
```

And my config.json just like this

```
{
  "maxMemory": {},
  "quantization": null,
  "models": {
    "ollama": {
      "modelWrapper": "AModelChatGPT",
      "apikey": "fake-key",
      "baseURL": "http://localhost:4000",
      "modelList": {
        "ollama/codestral:latest": {
          "formatter": "AFormatterGPT",
          "contextWindow": 8192,
          "systemAsUser": false
        }
      }
    }
  },
  "temperature": 8.0,
  "flashAttention2": false,
  "speechOn": false,
  "contextWindowRatio": 0.6,
  "services": {...}
}
```

**Comment by stevenlu137** [comment]
Is this your first time running AIlice? If so, it is likely due to the failure to download the embedding model weights for vecdb from Huggingface. If you are in China, please check your network settings. Otherwise, please run the following command and paste the output here:

```bash
python3 -m ailice.modules.AStorageVecDB --addr=ipc:///tmp/AIliceStorage.ipc
```

**Comment by ziyic** [comment]
Yes this is my first time running AIlice,and when I try to run the command provide above I got these info

```
❯ python3 -m ailice.modules.AStorageVecDB --addr=ipc:///tmp/AIliceStorage.ipc
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ailice/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/ailice/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ziyic/AIlice/ailice/modules/AStorageVecDB.py", line 117, in <module>
    main()
  File "/Users/ziyic/AIlice/ailice/modules/AStorageVecDB.py", line 114, in main
    makeServer(AStorageVecDB, dict(), args.addr, ["ModuleInfo", "Open", "Reset", "Store", "Query"]).Run()
  File "/Users/ziyic/AIlice/ailice/common/lightRPC.py", line 83, in makeServer
    return GenesisRPCServer(objCls,objArgs,url,APIList)
  File "/Users/ziyic/AIlice/ailice/common/lightRPC.py", line 39, in __init__
    self.receiver.bind(url)
  File "/opt/anaconda3/envs/ailice/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='ipc:///tmp/AIliceStorage.ipc')
```

**Comment by stevenlu137** [comment]
It seems that previously failed processes that didn't exit are interfering with running this command. Try terminating them first before running it again.

```bash
pkill -f ailice.modules
python3 -m ailice.modules.AStorageVecDB --addr=ipc:///tmp/AIliceStorage.ipc
```
