### ISSUE TITLE
Error: Connecting module browser FAILED

### ISSUE THREAD

**Issue by uniqueness-ae** [myshell-ai/AIlice#51]
Hello,

I am facing Connecting module browser FAILED issue. I am running this on MacBook Pro M1 and using conda and python version 3.11. Here are the details:

(AIlice) AK@MBP AIlice % ailice_web --modelID=groq:llama3-70b-8192
InitOpenRouterCfg() FAILED, skip this part and do not set it again.
********************** Initialize *****************************
config.json is located at /Users/AK/Library/Application Support/ailice
********************** End of Initialization *****************************
In order to simplify installation and usage, we have set local execution as the default behavior, which means AI has complete control over the local environment. To prevent irreversible losses due to potential AI errors, you may consider one of the following two methods: the first one, run AIlice in a virtual machine; the second one, install Docker, use the provided Dockerfile to build an image and container, and modify the relevant configurations in config.json. For detailed instructions, please refer to the documentation.
killing proc with PID 75993
killing proc with PID 75995
killing proc with PID 75996
killing proc with PID 75997
killing proc with PID 75999
storage  started.
browser  started.
arxiv  started.
google  started.
duckduckgo  started.
scripter  started.
computer  started.
Connecting module browser FAILED. You can try running the module manually and observe its error messages. EXCEPTION: Resource temporarily unavailable
Connecting module browser FAILED. You can try running the module manually and observe its error messages. EXCEPTION: Resource temporarily unavailable
Connecting module browser FAILED. You can try running the module manually and observe its error messages. EXCEPTION: Resource temporarily unavailable
Connecting module browser FAILED. You can try running the module manually and observe its error messages. EXCEPTION: Resource temporarily unavailable
Connecting module browser FAILED. You can try running the module manually and observe its error messages. EXCEPTION: Resource temporarily unavailable
It seems that some peripheral module services failed to start. EXCEPTION: Resource temporarily unavailable
  File "/Users/AK/AIlice/ailice/ui/app.py", line 59, in Init
    clientPool.Init()
  File "/Users/AK/AIlice/ailice/common/ARemoteAccessors.py", line 17, in Init
    raise e
  File "/Users/AK/AIlice/ailice/common/ARemoteAccessors.py", line 14, in Init
    self.pool[cfg['addr']] = makeClient(cfg['addr'])
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/AK/AIlice/ailice/common/lightRPC.py", line 138, in makeClient
    ret=ReceiveMsg(socket)
        ^^^^^^^^^^^^^^^^^^
  File "/Users/AK/AIlice/ailice/common/lightRPC.py", line 28, in ReceiveMsg
    return pickle.loads(conn.recv())
                        ^^^^^^^^^^^
  File "_zmq.py", line 1137, in zmq.backend.cython._zmq.Socket.recv
  File "_zmq.py", line 1172, in zmq.backend.cython._zmq.Socket.recv
  File "_zmq.py", line 1264, in zmq.backend.cython._zmq._recv_copy
  File "_zmq.py", line 1259, in zmq.backend.cython._zmq._recv_copy
  File "_zmq.py", line 152, in zmq.backend.cython._zmq._check_rc

Also I tried running this command as I saw it in another post: 
python3 -m ailice.modules.AStorageVecDB --addr=ipc:///tmp/AIliceStorage.ipc", "addr": "ipc:///tmp/AIliceStorage.ipc
Output:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/AK/AIlice/ailice/modules/AStorageVecDB.py", line 117, in <module>
    main()
  File "/Users/AK/AIlice/ailice/modules/AStorageVecDB.py", line 114, in main
    makeServer(AStorageVecDB, dict(), args.addr, ["ModuleInfo", "Open", "Reset", "Store", "Query"]).Run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/AK/AIlice/ailice/common/lightRPC.py", line 83, in makeServer
    return GenesisRPCServer(objCls,objArgs,url,APIList)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/AK/AIlice/ailice/common/lightRPC.py", line 39, in __init__
    self.receiver.bind(url)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/AIlice/lib/python3.11/site-packages/zmq/sugar/socket.py", line 311, in bind
    super().bind(addr)
  File "_zmq.py", line 895, in zmq.backend.cython._zmq.Socket.bind
zmq.error.ZMQError: No such file or directory for ipc path "/tmp/AIliceStorage.ipc, addr: ipc:///tmp/AIliceStorage.ipc". (addr='ipc:///tmp/AIliceStorage.ipc, addr: ipc:///tmp/AIliceStorage.ipc')

Hope someone can advise on a solution. Thanks

**Comment by stevenlu137** [comment]
Hello, you can use the latest code from the master branch. The new version provides more detailed error messages, making it easier to diagnose issues.

The second error appears to be caused by improper use of quotation marks. According to Ailice's output, the storage module has already started normally, so you can ignore the second error.

**Comment by uniqueness-ae** [comment]
Thank you @stevenlu137, I can confirm that the issue has been resolved after pulling the latest code.
